/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : CCD_SI.h
**     Project     : ProcessorExpert
**     Processor   : MKL25Z128VLK4
**     Component   : BitsIO
**     Version     : Component 02.108, Driver 01.00, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2013-05-10, 22:48, # CodeGen: 0
**     Abstract    :
**         This component "BitsIO" implements a multi-bit input/output.
**         It uses selected pins of one 1-bit to 8-bit port.
**         Note: This component is set to work in Output direction only.
**     Settings    :
**         Port name                   : PTC
**
**         Bit mask of the port        : 0x0600
**         Number of bits/pins         : 2
**         Single bit numbers          : 0 to 1
**         Values range                : 0 to 3
**
**         Initial direction           : Output (direction cannot be changed)
**         Initial output value        : 0 = 000H
**         Initial pull option         : off
**
**         Port data register          : GPIOC_PDOR [0x400FF080]
**         Port control register       : GPIOC_PDDR [0x400FF094]
**
**             ----------------------------------------------------
**                   Bit     |   Pin   |   Name
**             ----------------------------------------------------
**                    0      |    66   |   CMP0_IN3/PTC9/I2C0_SDA/TPM0_CH5
**                    1      |    67   |   PTC10/I2C1_SCL
**             ----------------------------------------------------
**
**         Optimization for            : speed
**     Contents    :
**         GetDir - bool CCD_SI_GetDir(void);
**         GetVal - byte CCD_SI_GetVal(void);
**         PutVal - void CCD_SI_PutVal(byte Val);
**         GetBit - bool CCD_SI_GetBit(byte Bit);
**         PutBit - void CCD_SI_PutBit(byte Bit, bool Val);
**         SetBit - void CCD_SI_SetBit(byte Bit);
**         ClrBit - void CCD_SI_ClrBit(byte Bit);
**         NegBit - void CCD_SI_NegBit(byte Bit);
**
**     Copyright : 1997 - 2012 Freescale, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

#ifndef __CCD_SI_H
#define __CCD_SI_H

/* MODULE CCD_SI. */

/* Include shared modules, which are used for whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited beans */
#include "BitsIoLdd1.h"

#include "Cpu.h"




/*
** ===================================================================
**     Method      :  CCD_SI_GetDir (component BitsIO)
**
**     Description :
**         This method returns direction of the component.
**     Parameters  : None
**     Returns     :
**         ---        - Direction of the component (always TRUE, Output only)
**                      FALSE = Input, TRUE = Output
** ===================================================================
*/
#define CCD_SI_GetDir() (BitsIoLdd1_GetDir(BitsIoLdd1_DeviceData))

/*
** ===================================================================
**     Method      :  CCD_SI_GetVal (component BitsIO)
**
**     Description :
**         This method returns an input value.
**           a) direction = Input  : reads the input value from the
**                                   pins and returns it
**           b) direction = Output : returns the last written value
**         Note: This component is set to work in Output direction only.
**     Parameters  : None
**     Returns     :
**         ---        - Input value (0 to 3)
** ===================================================================
*/
#define CCD_SI_GetVal() ((byte)BitsIoLdd1_GetVal(BitsIoLdd1_DeviceData))

/*
** ===================================================================
**     Method      :  CCD_SI_PutVal (component BitsIO)
**
**     Description :
**         This method writes the new output value.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Val        - Output value (0 to 3)
**     Returns     : Nothing
** ===================================================================
*/
#define CCD_SI_PutVal(Val) (BitsIoLdd1_PutVal(BitsIoLdd1_DeviceData, ((dword)(Val))))

bool CCD_SI_GetBit(byte Bit);
/*
** ===================================================================
**     Method      :  CCD_SI_GetBit (component BitsIO)
**
**     Description :
**         This method returns the specified bit of the input value.
**           a) direction = Input  : reads the input value from pins
**                                   and returns the specified bit
**           b) direction = Output : returns the specified bit
**                                   of the last written value
**         Note: This component is set to work in Output direction only.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to read (0 to 1)
**     Returns     :
**         ---        - Value of the specified bit (FALSE or TRUE)
**                      FALSE = "0" or "Low", TRUE = "1" or "High"
** ===================================================================
*/

/*
** ===================================================================
**     Method      :  CCD_SI_PutBit (component BitsIO)
**
**     Description :
**         This method writes the new value to the specified bit
**         of the output value.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit (0 to 1)
**         Val        - New value of the bit (FALSE or TRUE)
**                      FALSE = "0" or "Low", TRUE = "1" or "High"
**     Returns     : Nothing
** ===================================================================
*/
#define CCD_SI_PutBit(Bit,Val) ((void)BitsIoLdd1_PutBit(BitsIoLdd1_DeviceData, (Bit), (Val)))

/*
** ===================================================================
**     Method      :  CCD_SI_SetBit (component BitsIO)
**
**     Description :
**         This method sets (sets to one) the specified bit of the
**         output value.
**         [ It is the same as "PutBit(Bit,TRUE);" ]
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to set (0 to 1)
**     Returns     : Nothing
** ===================================================================
*/
#define CCD_SI_SetBit(Bit) ((void)BitsIoLdd1_SetBit(BitsIoLdd1_DeviceData, (Bit)))

/*
** ===================================================================
**     Method      :  CCD_SI_ClrBit (component BitsIO)
**
**     Description :
**         This method clears (sets to zero) the specified bit
**         of the output value.
**         [ It is the same as "PutBit(Bit,FALSE);" ]
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to clear (0 to 1)
**     Returns     : Nothing
** ===================================================================
*/
#define CCD_SI_ClrBit(Bit) ((void)BitsIoLdd1_ClrBit(BitsIoLdd1_DeviceData, (Bit)))

/*
** ===================================================================
**     Method      :  CCD_SI_NegBit (component BitsIO)
**
**     Description :
**         This method negates (inverts) the specified bit of the
**         output value.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to invert (0 to 31)
**     Returns     : Nothing
** ===================================================================
*/
#define CCD_SI_NegBit(Bit) ((void)BitsIoLdd1_NegBit(BitsIoLdd1_DeviceData, (Bit)))

/* END CCD_SI. */

#endif 
/* ifndef __CCD_SI_H */
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.0 [05.03]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
